### PR TITLE
feat: form component support zod

### PR DESCRIPTION
**Pull request by nonzzz**
## Checklist

- [x] Select
- [x] Radio
- [x] AutoComplete   
- [x] Checkbox
- [x] Counter
- [x] Switch
- [x] Slider
- [x] Rate

## Change information

All relative component was been done.

## Issues

#1750

### CODE REVIEW

**Comment by nonzzz** [comment]
@haoziqaq  Most of task has been done. But when i check the uploader component, i notice `useValidation` accept pass an api param, However, the current modification does not support `uploader`

**Comment by haoziqaq** [comment]
`Zod validation` does not require support for `apis args`, Thanks for the pr!

**Comment by chouchouji** [comment]
Can you add examples about zod in `example folder` for `autoComplete` and `uploader` component ?

**Comment by chouchouji** [comment]
Please update `rules` type in `types folder` for these form component. Thanks for your great work!

**Review by chouchouji — APPROVED** [review]

**Pull request merged**
