### PR TITLE
feat(swipe): support keyboard arrowLeft and arrowRight

### PR DESCRIPTION
**Pull request by chouchouji**
## Checklist

List of tasks you have already done and plan to do.

- [ ] Fix linting errors
- [ ] Tests have been added / updated (or snapshots)

## Change information

Describe your modifications here.

## Issues

The issues you want to close, formatted as close #1.

## Related Links

Links related to this pr.

### CODE REVIEW

**Comment by chouchouji** [comment]
@haoziqaq  我看swiper这里没有做节流 
image

https://github.com/nolimits4web/swiper/blob/master/src/modules/keyboard/keyboard.mjs#L19

**Comment by chouchouji** [comment]
@haoziqaq 我看swiperjs没有做节流处理

image

https://github.com/nolimits4web/swiper/blob/master/src/modules/keyboard/keyboard.mjs#L19

**Comment by haoziqaq** [comment]
那暂时按照目前的设计



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 7, 2024 10:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [varletjs/varlet] WIP(swipe): support keyboard arrowLeft andarrowRight (PR #1659)




 
@haoziqaq  我看swiper这里没有做节流
 image.png (view on web)
 
https://github.com/nolimits4web/swiper/blob/master/src/modules/keyboard/keyboard.mjs#L19

**Comment by chouchouji** [comment]
> 那暂时按照目前的设计
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jun 7, 2024 10:39 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [varletjs/varlet] WIP(swipe): support keyboard arrowLeft andarrowRight (PR #1659) @haoziqaq 我看swiper这里没有做节流 image.png (view on web) https://github.com/nolimits4web/swiper/blob/master/src/modules/keyboard/keyboard.mjs#L19 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

ok，我晚上补充一下测试用例

**Review by haoziqaq — APPROVED** [review]

**Pull request merged**
