### PR TITLE
docs(site): add migrate guide from 2.x and delete 1.x guide

### PR DESCRIPTION
**Pull request by chouchouji**
## Checklist

List of tasks you have already done and plan to do.

## Change information

Describe your modifications here.

## Issues

The issues you want to close, formatted as close #1.

## Related Links

Links related to this pr.

### CODE REVIEW

**Comment by haoziqaq** [comment]
Keep only content migrated from 2.x.

**Comment by chouchouji** [comment]
> Keep only content migrated from 2.x.

Get, I will add rest ui component tomorrow and remove non-related code

**Comment by chouchouji** [comment]
> Keep only content migrated from 2.x.

I had delete the guide about migrating from 1.x

**Comment by chouchouji** [comment]
> > Keep only content migrated from 2.x.
> 
> I had deleted the guide about migrating from 1.x

**Pull request closed without merging**
