### PR TITLE
feat(time-picker): support actions slot

### LINKED ISSUE #1333: [timePicker] add action buttons
[related issue](https://github.com/varletjs/varlet/issues/1273)
[related pr](https://github.com/varletjs/varlet/pull/1321)

### PR DESCRIPTION
**Pull request by pureStyles**
## Checklist

List of tasks you have already done and plan to do.

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

Describe your modifications here.
- add slot named actions in the bottom area

## Issues

The issues you want to close, formatted as close #1333 .

## Related Links

Links related to this pr.

### CODE REVIEW

**Comment by chouchouji** [comment]
该 pr 加了 css var，需要运行下 `pnpm compile`以导出 css var 样式的类型文件

**Comment by pureStyles** [comment]
> 该 pr 加了 css var，需要运行下 `pnpm compile`以导出 css var 样式的类型文件

**Comment by pureStyles** [comment]
> 该 pr 加了 css var，需要运行下 `pnpm compile`以导出 css var 样式的类型文件

done-.-

**Review by BeADre — APPROVED** [review]

**Comment by BeADre** [comment]
@haoziqaq  可以合了

**Comment by pureStyles** [comment]
@BeADre 辛苦大佬review与调整🤣

**Pull request merged**
