### PR TITLE
chore(playground): Solve the problem that the component library must be manually introduced into the playground user code editing area

### PR DESCRIPTION
**Pull request by CharlesChanV**
## Checklist

---

- [ ] Fix linting errors
- [ ] Tests have been added / updated (or snapshots)

## Change information
Solve the problem that the component library must be manually introduced into the playground user code editing area
---

### CODE REVIEW

**Comment by haoziqaq** [comment]
This may affect the downloaded code package, you can try to see if it works after downloading the code.
if not, fix it and pr to the v2.0 branch

**Comment by CharlesChanV** [comment]
> This may affect the downloaded code package, you can try to see if it works after downloading the code. if not, fix it and pr to the v2.0 branch

@haoziqaq hello guy, i have check the change and it works well(https://varlet-ui-playground-1mzek8i61-varletjs.vercel.app), should i pr to the v2.0 or not? i have ask a member from group, and he told me just pr to the dev branch

**Comment by haoziqaq** [comment]
image

1.Playground.vue is not needed
2.pr to the v2.0 branch trust me

**Comment by haoziqaq** [comment]
ok, please pr to the v2.0 branch, thx

**Comment by CharlesChanV** [comment]
> ok, please pr to the v2.0 branch, thx

@haoziqaq ihas changed the branch~

**Pull request merged**
