### PR TITLE
feat(ui/table): support --table-thead-th-text-align

### PR DESCRIPTION
**Pull request by Aybrea**
## Checklist

List of tasks you have already done and plan to do.

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

Add text align css variable for table head th and correct some md writing.

### CODE REVIEW

**Comment by haoziqaq** [comment]
Theme files should also be changed

**Comment by chouchouji** [comment]
run `pnpm run compile:style-vars` to add missing type

**Comment by Aybrea** [comment]
done adding styleVars

**Comment by Aybrea** [comment]
done modifying theme files

**Comment by chouchouji** [comment]
need to update snapshot

**Review by chouchouji — APPROVED** [review]

**Pull request merged**
