### PR TITLE
feat(ui/divider): add hairline divider

### PR DESCRIPTION
**Pull request by a145789**
## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information 
 add hairline divider

### CODE REVIEW

**Comment by haoziqaq** [comment]
Will the description text be affected when using a 0.5px divider

**Comment by haoziqaq** [comment]
Will the description text be affected when using a 0.5px divider?

**Comment by a145789** [comment]
Yes. I used the new css, which no longer affects the description text. There should be no need to display text in vertical mode, so I just changed normal mode.

**Comment by haoziqaq** [comment]
nice work~ thx

**Pull request merged**
