### PR TITLE
feat: support hsl css var

### PR DESCRIPTION
**Pull request by chouchouji**
## Checklist

List of tasks you have already done and plan to do.

- [ ] Fix linting errors
- [ ] Tests have been added / updated (or snapshots)

## Change information

Describe your modifications here.

## Issues

The issues you want to close, formatted as close #1.

## Related Links

Links related to this pr.

### CODE REVIEW

**Comment by chouchouji** [comment]
It need to complete the code about tailwindcss and unocss preset

**Comment by haoziqaq** [comment]
We may need to introduce users to benefits of the `hsl-based` css variables. How about writing it in the documentation?

**Comment by haoziqaq** [comment]
In additions, we do not force users to choose `hsl-based`, we just explain why we do so.

**Comment by chouchouji** [comment]
> In additions, we do not force users to choose `hsl-based`, we just explain why we do so.

I will add it here and `varlet-install-example` repo

image

**Review by haoziqaq — APPROVED** [review]

**Pull request merged**
